### PR TITLE
Update runtime for ROCm6.0 (SWDEV-434155)

### PR DESCRIPTION
**Pull request by AdrianAbeyta**
This PR enables CuPy to use the updated API's in hip/cupy_hip_runtime.h for ROCm6.0. 

- Fixes issues related to https://ontrack-internal.amd.com/browse/SWDEV-434155:
  - Addresses changes  for the removal of "memoryType" in hipPointerAttribute_t
  - Added support for using updated "gcnArchName" 
  - Updates GitHub runner ci/cd

### CODE REVIEW

**Review by lcskrishna — APPROVED** [review]
LGTM! Ideally this change shouldn't affect anything in the master branch.

**Review by pnunna93 — APPROVED** [review]
LGTM

**Review by amathews-amd — APPROVED** [review]
LGTM

**Review by bmedishe — COMMENTED** [review]
All UTs pass except for 1486 failed : tests/cupyx_tests/scipy_tests/signal_tests  which are seen failing in master branch too

**Comment by lcskrishna** [comment]
Passing log: 
https://amdcloud-my.sharepoint.com/:u:/g/personal/csrikris_amd_com/EU4ofnSXhulHkls1k-G6geUBFOiHy2nVh3swfyglRS62_w?e=ucYqhn

**Pull request merged**
