### PR TITLE
Hip solver lazy loading

### PR DESCRIPTION
**Pull request by bmedishe**

### CODE REVIEW

**Comment by bmedishe** [comment]
[cupy_tests_cuda_tests_test_cusolver.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321556/cupy_tests_cuda_tests_test_cusolver.log)
[cupy_tests_cuda_tests_test_device.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321557/cupy_tests_cuda_tests_test_device.log)
[cupy_tests_cuda_tests_test_graph.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321558/cupy_tests_cuda_tests_test_graph.log)
[cupy_tests_linalg_tests_test_decomposition.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321559/cupy_tests_linalg_tests_test_decomposition.log)
[cupyx_tests_linalg_tests_test_solve.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321560/cupyx_tests_linalg_tests_test_solve.log)
[cupyx_tests_test_cusolver.txt](https://github.com/ROCmSoftwarePlatform/cupy/files/13310263/cupyx_tests_test_cusolver.txt)
[cupyx_tests_test_lapack.txt](https://github.com/ROCmSoftwarePlatform/cupy/files/13310264/cupyx_tests_test_lapack.txt)
All tests using cusolver pass 
[cupyx_tests_scipy_tests_sparse_tests_test_linalg.log](https://github.com/ROCmSoftwarePlatform/cupy/files/13321561/cupyx_tests_scipy_tests_sparse_tests_test_linalg.log)

**Comment by lcskrishna** [comment]
@bmedishe Could you run ```pre-commit run --all-files``` in your local setup and fix all the flake8 or any coding standard issues. This will clear static-tests CI failures.

**Comment by lcskrishna** [comment]
For ROCm builds, could you please cherry-pick or port these changes into your PR. 
https://github.com/ROCmSoftwarePlatform/cupy/pull/18/files#diff-def21d65b1bcf0fdd594272d80964de16c0b7d8bffbebd488839499b874a63f4

**Comment by bmedishe** [comment]
> For ROCm builds, could you please cherry-pick or port these changes into your PR. https://github.com/ROCmSoftwarePlatform/cupy/pull/18/files#diff-def21d65b1bcf0fdd594272d80964de16c0b7d8bffbebd488839499b874a63f4

Thank you Chaitanya @lcskrishna  , I updated PR for the above comments

**Comment by lcskrishna** [comment]
@bmedishe Let's re-run the whole test suite again with the newer changes and attach the passing log here. This way we can identify if there are any regressions early on since we are moving to the newer design.

**Review by AdrianAbeyta — APPROVED** [review]
LGTM

**Pull request merged**
